# Generated by Django 3.1.2 on 2020-10-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=50)),
                ('primer_nombre', models.CharField(max_length=200)),
                ('segundo_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(blank=True, max_length=200, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=12, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('especialidad', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('discapacidad', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=255, null=True)),
                ('celular', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('archivo_titulo', models.FileField(blank=True, null=True, upload_to='titulos/')),
                ('estado_civil', models.ManyToManyField(to='principal.EstadoCivil')),
            ],
        ),
    ]
