# Generated by Django 3.1.2 on 2020-10-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='experiencia_laboral',
            field=models.FileField(blank=True, null=True, upload_to='experiencia_laboral/'),
        ),
    ]
