# Generated by Django 3.1.2 on 2020-10-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20201029_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='validacion',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(error_messages={'unique': 'Ya existe el número de Cédula'}, max_length=50, unique=True),
        ),
    ]
