# Generated by Django 3.1.2 on 2020-10-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20201029_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='validacion',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True),
        ),
    ]
